version: '3.1'

services:
  mongo:
    image: docker.arvancloud.ir/mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: boresh
    # MONGO_INITDB_ROOT_PASSWORD: boresh

  mongo-express:
    image: docker.arvancloud.ir/mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME:
      ME_CONFIG_MONGODB_ADMINPASSWORD:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
