version: '3.1'

services:
  mongo:
    image: docker.arvancloud.ir/mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: boresh
    # MONGO_INITDB_ROOT_PASSWORD: boresh
