version: '3.1'

services:
  redis:
    image: docker.arvancloud.ir/redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379

  mongo:
    image: docker.arvancloud.ir/mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: boresh
    # MONGO_INITDB_ROOT_PASSWORD: boresh

volumes:
  mongo:
  redis:
