version: '3.1'

services:
  redis:
    image: docker.arvancloud.ir/redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  mongo:
    image: docker.arvancloud.ir/mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: boresh
    # MONGO_INITDB_ROOT_PASSWORD: boresh

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

volumes:
  mongo:
  redis:
